import Head from "next/head";
import styles from "../styles/Home.module.css";
import InstaFooter from "./main/footer/Footer";
import MainContent from "./main/mainContent/MainContent";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Instagram</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link
          href="http://fonts.googleapis.com/css?family=Roboto"
          rel="stylesheet"
          type="text/css"
        ></link>
      </Head>

      <main className={styles.main}>
        <MainContent></MainContent>
      </main>

      <InstaFooter />
    </div>
  );
}
